[2024-08-26T08:28:44.548+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T08:28:44.578+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:43.653426+00:00 [queued]>
[2024-08-26T08:28:44.600+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:43.653426+00:00 [queued]>
[2024-08-26T08:28:44.601+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-26T08:28:44.624+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-26 08:28:43.653426+00:00
[2024-08-26T08:28:44.632+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=792) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T08:28:44.633+0000] {standard_task_runner.py:72} INFO - Started process 793 to run task
[2024-08-26T08:28:44.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_and_transform_dag', 'run_python_script', 'manual__2024-08-26T08:28:43.653426+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Dags.py', '--cfg-path', '/tmp/tmpkwgmfq27']
[2024-08-26T08:28:44.634+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask run_python_script
[2024-08-26T08:28:44.710+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:43.653426+00:00 [running]> on host 6ac8cf047f5e
[2024-08-26T08:28:44.834+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_transform_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T08:28:43.653426+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T08:28:43.653426+00:00'
[2024-08-26T08:28:44.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T08:28:44.856+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-26T08:28:44.858+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-26T08:28:44.882+0000] {subprocess.py:86} INFO - Output:
[2024-08-26T08:28:46.564+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/customers.csv: [Errno 13] Permission denied: '/data/customers.csv'
[2024-08-26T08:28:46.565+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/accounts.csv: [Errno 13] Permission denied: '/data/accounts.csv'
[2024-08-26T08:28:46.567+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/transactions.csv: [Errno 13] Permission denied: '/data/transactions.csv'
[2024-08-26T08:28:46.569+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/branches.csv: [Errno 13] Permission denied: '/data/branches.csv'
[2024-08-26T08:28:46.570+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/loans.csv: [Errno 13] Permission denied: '/data/loans.csv'
[2024-08-26T08:28:46.571+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/credit_cards.csv: [Errno 13] Permission denied: '/data/credit_cards.csv'
[2024-08-26T08:28:46.572+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/transaction_history.csv: [Errno 13] Permission denied: '/data/transaction_history.csv'
[2024-08-26T08:28:46.573+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/payment.csv: [Errno 13] Permission denied: '/data/payment.csv'
[2024-08-26T08:28:46.574+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/investments.csv: [Errno 13] Permission denied: '/data/investments.csv'
[2024-08-26T08:28:46.718+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-26T08:28:46.766+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T08:28:46.768+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_and_transform_dag, task_id=run_python_script, run_id=manual__2024-08-26T08:28:43.653426+00:00, execution_date=20240826T082843, start_date=20240826T082844, end_date=20240826T082846
[2024-08-26T08:28:46.825+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-26T08:28:46.858+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T08:28:46.861+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
