[2024-08-26T08:28:02.965+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T08:28:03.034+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:00.790574+00:00 [queued]>
[2024-08-26T08:28:03.063+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:00.790574+00:00 [queued]>
[2024-08-26T08:28:03.065+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-26T08:28:03.102+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-26 08:28:00.790574+00:00
[2024-08-26T08:28:03.113+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_and_transform_dag', 'run_python_script', 'manual__2024-08-26T08:28:00.790574+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Dags.py', '--cfg-path', '/tmp/tmpmfdqh2je']
[2024-08-26T08:28:03.115+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=762) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T08:28:03.115+0000] {standard_task_runner.py:105} INFO - Job 190: Subtask run_python_script
[2024-08-26T08:28:03.116+0000] {standard_task_runner.py:72} INFO - Started process 773 to run task
[2024-08-26T08:28:03.226+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_and_transform_dag.run_python_script manual__2024-08-26T08:28:00.790574+00:00 [running]> on host 6ac8cf047f5e
[2024-08-26T08:28:03.450+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_transform_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T08:28:00.790574+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T08:28:00.790574+00:00'
[2024-08-26T08:28:03.454+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T08:28:03.541+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-26T08:28:03.545+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-26T08:28:03.569+0000] {subprocess.py:86} INFO - Output:
[2024-08-26T08:28:05.729+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/customers.csv: [Errno 13] Permission denied: '/data/customers.csv'
[2024-08-26T08:28:05.731+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/accounts.csv: [Errno 13] Permission denied: '/data/accounts.csv'
[2024-08-26T08:28:05.731+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/transactions.csv: [Errno 13] Permission denied: '/data/transactions.csv'
[2024-08-26T08:28:05.732+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/branches.csv: [Errno 13] Permission denied: '/data/branches.csv'
[2024-08-26T08:28:05.733+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/loans.csv: [Errno 13] Permission denied: '/data/loans.csv'
[2024-08-26T08:28:05.734+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/credit_cards.csv: [Errno 13] Permission denied: '/data/credit_cards.csv'
[2024-08-26T08:28:05.735+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/transaction_history.csv: [Errno 13] Permission denied: '/data/transaction_history.csv'
[2024-08-26T08:28:05.736+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/payment.csv: [Errno 13] Permission denied: '/data/payment.csv'
[2024-08-26T08:28:05.737+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /data/investments.csv: [Errno 13] Permission denied: '/data/investments.csv'
[2024-08-26T08:28:05.887+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-26T08:28:05.956+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T08:28:05.958+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_and_transform_dag, task_id=run_python_script, run_id=manual__2024-08-26T08:28:00.790574+00:00, execution_date=20240826T082800, start_date=20240826T082803, end_date=20240826T082805
[2024-08-26T08:28:06.016+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-26T08:28:06.058+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T08:28:06.061+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
